 const citiesWithCountry = [
    { "name": "New York", "country": "US" },
    { "name": "London", "country": "UK" },
    { "name": "Paris", "country": "FR" },
    { "name": "Tokyo", "country": "JP" },
    { "name": "Los Angeles", "country": "US" },
    { "name": "Chicago", "country": "US" },
    { "name": "Moscow", "country": "RU" },
    { "name": "Shanghai", "country": "CN" },
    { "name": "Beijing", "country": "CN" },
    { "name": "Berlin", "country": "DE" },
    { "name": "Madrid", "country": "ES" },
    { "name": "Rome", "country": "IT" },
    { "name": "Toronto", "country": "CA" },
    { "name": "Sydney", "country": "AU" },
    { "name": "Seoul", "country": "KR" },
    { "name": "Mexico City", "country": "MX" },
    { "name": "São Paulo", "country": "BR" },
    { "name": "Mumbai", "country": "IN" },
    { "name": "Delhi", "country": "IN" },
    { "name": "Bangalore", "country": "IN" },
    { "name": "Hyderabad", "country": "IN" },
    { "name": "Ahmedabad", "country": "IN" },
    { "name": "Chennai", "country": "IN" },
    { "name": "Kolkata", "country": "IN" },
    { "name": "Surat", "country": "IN" },
    { "name": "Pune", "country": "IN" },
    { "name": "Jaipur", "country": "IN" },
    { "name": "Lucknow", "country": "IN" },
    { "name": "Kanpur", "country": "IN" },
    { "name": "Nagpur", "country": "IN" },
    { "name": "Visakhapatnam", "country": "IN" },
    { "name": "Indore", "country": "IN" },
    { "name": "Thane", "country": "IN" },
    { "name": "Bhopal", "country": "IN" },
    { "name": "Patna", "country": "IN" },
    { "name": "Vadodara", "country": "IN" },
    { "name": "Ghaziabad", "country": "IN" },
    { "name": "Ludhiana", "country": "IN" },
    { "name": "Agra", "country": "IN" },
    { "name": "Nashik", "country": "IN" },
    { "name": "Faridabad", "country": "IN" },
    { "name": "Meerut", "country": "IN" },
    { "name": "Rajkot", "country": "IN" },
    { "name": "Kalyan-Dombivali", "country": "IN" },
    { "name": "Vasai-Virar", "country": "IN" },
    { "name": "Varanasi", "country": "IN" },
    { "name": "Srinagar", "country": "IN" },
    { "name": "Aurangabad", "country": "IN" },
    { "name": "Dhanbad", "country": "IN" },
    { "name": "Amritsar", "country": "IN" },
    { "name": "Navi Mumbai", "country": "IN" },
    { "name": "Allahabad", "country": "IN" },
    { "name": "Ranchi", "country": "IN" },
    { "name": "Howrah", "country": "IN" },
    { "name": "Coimbatore", "country": "IN" },
    { "name": "Jabalpur", "country": "IN" },
    { "name": "Gwalior", "country": "IN" },
    { "name": "Vijayawada", "country": "IN" },
    { "name": "Jodhpur", "country": "IN" },
    { "name": "Madurai", "country": "IN" },
    { "name": "Raipur", "country": "IN" },
    { "name": "Kota", "country": "IN" },
    { "name": "Chandigarh", "country": "IN" },
    { "name": "Guwahati", "country": "IN" },
    { "name": "Solapur", "country": "IN" },
    { "name": "Hubli-Dharwad", "country": "IN" },
    { "name": "Istanbul", "country": "TR" },
    { "name": "Ankara", "country": "TR" },
    { "name": "Izmir", "country": "TR" },
    { "name": "Bursa", "country": "TR" },
    { "name": "Adana", "country": "TR" },
    { "name": "Bangkok", "country": "TH" },
    { "name": "Nonthaburi", "country": "TH" },
    { "name": "Nakhon Ratchasima", "country": "TH" },
    { "name": "Chiang Mai", "country": "TH" },
    { "name": "Udon Thani", "country": "TH" },
    { "name": "Beijing", "country": "CN" },
    { "name": "Shanghai", "country": "CN" },
    { "name": "Guangzhou", "country": "CN" },
    { "name": "Shenzhen", "country": "CN" },
    { "name": "Wuhan", "country": "CN" },
    { "name": "Cairo", "country": "EG" },
    { "name": "Alexandria", "country": "EG" },
    { "name": "Giza", "country": "EG" },
    { "name": "Port Said", "country": "EG" },
    { "name": "Suez", "country": "EG" },
    { "name": "Rio de Janeiro", "country": "BR" },
    { "name": "São Paulo", "country": "BR" },
    { "name": "Brasília", "country": "BR" },
    { "name": "Salvador", "country": "BR" },
    { "name": "Fortaleza", "country": "BR" },
    { "name": "Mexico City", "country": "MX" },
    { "name": "Ecatepec", "country": "MX" },
    { "name": "Guadalajara", "country": "MX" },
    { "name": "Puebla", "country": "MX" },
    { "name": "Juárez", "country": "MX" },
    { "name": "Buenos Aires", "country": "AR" },
    { "name": "Córdoba", "country": "AR" },
    { "name": "Rosario", "country": "AR" },
    { "name": "Mendoza", "country": "AR" },
    { "name": "San Miguel de Tucumán", "country": "AR" },
    { "name": "Jakarta", "country": "ID" },
    { "name": "Surabaya", "country": "ID" },
    { "name": "Bandung", "country": "ID" },
    { "name": "Medan", "country": "ID" },
    { "name": "Palembang", "country": "ID" },
    { "name": "Lagos", "country": "NG" },
    { "name": "Kano", "country": "NG" },
    { "name": "Ibadan", "country": "NG" },
    { "name": "Kaduna", "country": "NG" },
    { "name": "Port Harcourt", "country": "NG" },
    { "name": "Lima", "country": "PE" },
    { "name": "Arequipa", "country": "PE" },
    { "name": "Callao", "country": "PE" },
    { "name": "Trujillo", "country": "PE" },
    { "name": "Chiclayo", "country": "PE" },
    { "name": "Santiago", "country": "CL" },
    { "name": "Puente Alto", "country": "CL" },
    { "name": "Maipú", "country": "CL" },
    { "name": "Antofagasta", "country": "CL" },
    { "name": "Viña del Mar", "country": "CL" },
    { "name": "Bangalore", "country": "IN" },
    { "name": "Chennai", "country": "IN" },
    { "name": "Kolkata", "country": "IN" },
    { "name": "Ahmedabad", "country": "IN" },
    { "name": "Bengaluru", "country": "IN" },
    { "name": "Johannesburg", "country": "ZA" },
    { "name": "Cape Town", "country": "ZA" },
    { "name": "Durban", "country": "ZA" },
    { "name": "Pretoria", "country": "ZA" },
    { "name": "Port Elizabeth", "country": "ZA" },
];

export default citiesWithCountry;
